
package in.malonus.ws;

import java.util.concurrent.TimeUnit;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-02-21T22:01:23.128+08:00
 * Generated source version: 2.6.2
 * 
 */
 
public class SimpleService_P1_Server{

    protected SimpleService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SimpleServiceImpl();
        String address = "http://localhost:8080/ws/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SimpleService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(TimeUnit.MINUTES.toMillis(5)); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
